import streamlit as st
import os
import requests
import json
from PyPDF2 import PdfReader
from dotenv import load_dotenv
import time
from fpdf import FPDF
from datetime import datetime

# --- Setup ---
load_dotenv()

# Configuration
KILO_API_URL = "https://api.kilo.ai/api/gateway/chat/completions"
DEFAULT_MODEL = "kilo-auto/free"

# --- PDF Generator ---
def create_pdf_report(info, evaluation, transcript, photo_bytes=None):
    pdf = FPDF()
    pdf.add_page()
    
    # Extract Decision for PDF Styling
    is_pass = "PASS" in str(evaluation).upper()
    decision_color = (16, 185, 129) if is_pass else (239, 68, 68)
    decision_text = "INTERVIEW STATUS: PASS" if is_pass else "INTERVIEW STATUS: FAIL"

    # 🖼️ Page Border
    pdf.set_line_width(0.5)
    pdf.rect(5, 5, 200, 287)
    
    # 🏢 Header Section
    pdf.set_fill_color(240, 246, 255)
    pdf.rect(10, 10, 190, 40, 'F')
    
    # 📸 Embedding Photo (if available)
    if photo_bytes:
        import tempfile
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
            tmp.write(photo_bytes.getvalue())
            tmp_path = tmp.name
        try:
            pdf.image(tmp_path, 165, 12, 30, 30)
            os.unlink(tmp_path)
        except: pass

    # ✍️ Title & branding
    pdf.set_font('Arial', 'B', 22)
    pdf.set_text_color(37, 99, 235)
    pdf.set_xy(15, 15)
    pdf.cell(140, 10, 'MANVER AI INTERVIEW', 0, 1, 'L')
    
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.set_x(15)
    pdf.cell(140, 10, f"INTERVIEW REPORT | {st.session_state.interview_time}", 0, 1, 'L')
    
    # 👤 Candidate Profile Box
    pdf.ln(15)
    pdf.set_fill_color(250, 250, 250)
    pdf.rect(10, 55, 190, 35, 'F')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.set_xy(15, 60)
    pdf.cell(90, 8, f"NAME: {info.get('name', 'N/A').upper()}", 0, 0)
    pdf.cell(90, 8, f"ID: {info.get('id', 'N/A').upper()}", 0, 1)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_x(15)
    pdf.cell(90, 8, f"EMAIL: {info.get('email', 'N/A')}", 0, 0)
    pdf.cell(90, 8, f"PHONE: {info.get('phone', 'N/A')}", 0, 1)
    
    # 🎯 DECISION BADGE (in PDF)
    pdf.set_fill_color(*decision_color)
    pdf.rect(10, 95, 190, 15, 'F')
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 95)
    pdf.cell(190, 15, decision_text, 0, 1, 'C')

    # 🧠 AI Evaluation Section
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 10, 'AI PERFORMANCE EVALUATION', 'B', 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(51, 65, 85)
    eval_text = str(evaluation).encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, eval_text)
    
    # 📖 Transcript Section
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 10, 'INTERVIEW TRANSCRIPT', 'B', 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(71, 85, 105)
    trans_text = str(transcript).encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 6, trans_text)
    
    pdf.set_y(-15)
    pdf.set_font('Arial', 'I', 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, 'Confidentially generated by Manver AI Interviewing System - (c) 2026', 0, 0, 'C')

    return pdf.output(dest='S').encode('latin-1')

# --- Styling (Glassmorphism) ---
st.set_page_config(page_title="Manver AI Interviewer", page_icon="🤖", layout="wide")

st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&family=Outfit:wght@400;700&display=swap');
    
    :root {
        --color-bg: #0f172a;
        --color-primary: #3b82f6;
        --color-secondary: #64748b;
        --color-accent: #10b981;
        --color-glass: rgba(30, 41, 59, 0.7);
        --color-border: rgba(255, 255, 255, 0.1);
    }
    
    .stApp {
        background: radial-gradient(circle at 10% 20%, #1e293b 0%, #0f172a 90%);
        color: #f1f5f9;
        font-family: 'Inter', sans-serif;
    }
    
    .glass-card {
        background: var(--color-glass);
        backdrop-filter: blur(12px);
        border: 1px solid var(--color-border);
        border-radius: 1.25rem;
        padding: 1.5rem;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);
        margin-bottom: 1.5rem;
    }
    
    .stButton > button {
        border-radius: 0.75rem !important;
        font-weight: 600 !important;
        transition: all 0.2s ease !important;
        border: 1px solid rgba(255,255,255,0.1) !important;
        padding: 0.5rem 1rem !important;
    }

    /* Primary buttons */
    div[data-testid="stButton"] button[kind="primary"] {
        background: linear-gradient(135deg, #3b82f6, #2563eb) !important;
        box-shadow: 0 4px 12px rgba(37, 99, 235, 0.3) !important;
    }

    /* Secondary/Default buttons */
    div[data-testid="stButton"] button[kind="secondary"] {
        background: rgba(255, 255, 255, 0.05) !important;
        color: #fff !important;
    }
    
    div[data-testid="stButton"] button:hover {
        transform: translateY(-1px);
        filter: brightness(1.1);
    }

    h1, h2, h3 {
        font-family: 'Outfit', sans-serif !important;
        background: linear-gradient(to right, #60a5fa, #3b82f6);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 700 !important;
        margin-bottom: 1rem !important;
    }
    
    .stProgress > div > div > div > div {
        background: linear-gradient(to right, #3b82f6, #10b981) !important;
    }
    
    /* Remove white borders/boxes from streamlit */
    div[data-testid="stVerticalBlockBorderWrapper"] { border: none !important; }
    
    /* Clean up the text area */
    .stTextArea textarea {
        background: rgba(0, 0, 0, 0.2) !important;
        border: 1px solid rgba(255, 255, 255, 0.1) !important;
        border-radius: 0.75rem !important;
        color: white !important;
    }
    </style>
""", unsafe_allow_html=True)

# --- AI & Parsing Helpers ---
def get_api_key(): return os.getenv("VITE_KILO_API_KEY") or os.getenv("KILO_API_KEY")

def call_ai(messages, model=DEFAULT_MODEL):
    api_key = get_api_key()
    headers = {"Content-Type": "application/json"}
    if api_key: headers["Authorization"] = f"Bearer {api_key}"
    try:
        res = requests.post(KILO_API_URL, headers=headers, json={"model": model, "messages": messages, "temperature": 0.7, "max_tokens": 1200}, timeout=45)
        if res.status_code == 200:
            return res.json()["choices"][0]["message"]["content"]
        else:
            st.error(f"API Error: {res.status_code} - See details in console")
            return None
    except Exception as e:
        st.error(f"Network Error: {str(e)}")
        return None

def extract_text_from_pdf(file):
    reader = PdfReader(file)
    text = ""
    for page in reader.pages: text += page.extract_text()
    return text

# --- State ---
if 'step' not in st.session_state: st.session_state.step = 'setup'
# Ensure user_info exists and has all required keys (fixing potential old session issues)
if 'user_info' not in st.session_state:
    st.session_state.user_info = {"name": "", "email": "", "phone": "", "id": ""}
else:
    for key in ["name", "email", "phone", "id"]:
        if key not in st.session_state.user_info:
            st.session_state.user_info[key] = ""

if 'analysis' not in st.session_state: st.session_state.analysis = ""
if 'questions' not in st.session_state: st.session_state.questions = []
if 'answers' not in st.session_state: st.session_state.answers = []
if 'current_q' not in st.session_state: st.session_state.current_q = 0
if 'persistent_photo' not in st.session_state: st.session_state.persistent_photo = None
if 'interview_time' not in st.session_state: st.session_state.interview_time = None

# --- Pages ---
@st.dialog("Submit Interview?")
def confirm_submission():
    st.write("Are you sure you want to complete the interview? You won't be able to change your answers after this.")
    c1, c2 = st.columns(2)
    if c1.button("✅ Yes, Submit", use_container_width=True, type="primary"):
        with st.status("🚀 Processing submission...", expanded=True) as s:
            st.write("Gathering responses...")
            time.sleep(0.5)
            st.write("Finalizing session...")
            st.session_state.step = 'report'
        st.rerun()
    if c2.button("❌ No, Go Back", use_container_width=True):
        st.rerun()

def show_setup():
    st.title("🤖 Manver AI Interviewer")
    
    # JavaScript to move to next field on Enter
    st.markdown("""
        <script>
        function setupEnterNavigation() {
            const inputs = window.parent.document.querySelectorAll('input[type="text"]');
            inputs.forEach((input, index) => {
                input.addEventListener('keydown', (e) => {
                    if (e.key === 'Enter') {
                        e.preventDefault();
                        const next = inputs[index + 1];
                        if (next) {
                            next.focus();
                        } else {
                            // If last text field, blur to ensure sync and then click start
                            input.blur();
                            setTimeout(() => {
                                const btn = window.parent.document.querySelector('button[kind="primary"]');
                                if (btn) btn.click();
                            }, 100);
                        }
                    }
                });
            });
        }
        // Run setup once DOM is ready
        if (!window.enterNavSetup) {
            setTimeout(setupEnterNavigation, 1000);
            window.enterNavSetup = true;
        }
        </script>
    """, unsafe_allow_html=True)
    
    c1, c2 = st.columns([1, 1], gap="medium")
    
    with c1:
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        st.write("### 👤 Candidate Details")
        
        # Using session state keys for robust validation
        name = st.text_input("Full Name *", key="reg_name", placeholder="John Doe")
        email = st.text_input("Email ID *", key="reg_email", placeholder="john@example.com")
        c_id = st.text_input("Candidate ID *", key="reg_id", placeholder="CAND-001")
        phone = st.text_input("Phone Number *", key="reg_phone", placeholder="+91 XXXX XXXX")
        
        st.write("### 📄 Resume Analysis")
        uploaded_file = st.file_uploader("Upload PDF *", type=['pdf'], label_visibility="collapsed")
        model = st.selectbox("Model", ["kilo-auto/free", "minimax/minimax-m2.5:free"], label_visibility="collapsed")
        
        if st.button("🚀 Start Interview", type="primary", use_container_width=True):
            # Check session state directly to avoid sync issues from JS clicks
            v_name = st.session_state.get("reg_name", "").strip()
            v_email = st.session_state.get("reg_email", "").strip()
            v_id = st.session_state.get("reg_id", "").strip()
            v_phone = st.session_state.get("reg_phone", "").strip()
            
            # Specific and clear error messaging
            if not v_name or not v_email or not v_id or not v_phone:
                st.error("⚠️ All candidate detail fields are mandatory. Please fill them out.")
            elif not uploaded_file:
                st.error("📄 Please upload your resume (PDF) to proceed.")
            elif not st.session_state.persistent_photo:
                st.error("📸 Identity verification is mandatory! Please capture your photo using the 'System Check' camera on the right.")
            else:
                st.session_state.user_info = {"name": v_name, "email": v_email, "id": v_id, "phone": v_phone}
                from datetime import datetime
                st.session_state.interview_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                
                with st.spinner("Analyzing profile..."):
                    text = extract_text_from_pdf(uploaded_file)
                    res = call_ai([{"role": "system", "content": "Analyze resume."}, {"role": "user", "content": text}], model=model)
                    if res:
                        st.session_state.analysis = res
                        st.session_state.step = 'analysis'
                        st.rerun()
        st.markdown('</div>', unsafe_allow_html=True)

    with c2:
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        st.write("### 📹 System Check")
        st.info("Identity verification is mandatory.")
        
        # Using a separate key and saving it immediately to persistence
        cam_img = st.camera_input("Verify Identity", key="setup_camera")
        if cam_img:
            st.session_state.persistent_photo = cam_img
            st.success("✅ Identity Captured!")
        elif st.session_state.persistent_photo:
            st.image(st.session_state.persistent_photo, caption="Verification Preview")
            
        st.markdown("""
            <div style="margin-top: 2rem; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 1rem;">
                <strong>🎙️ Audio Check:</strong> Microphone and Camera permissions are required for the live session.
            </div>
        """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

def show_analysis():
    st.title("🔍 Candidate Insights")
    st.markdown(f'<div class="glass-card">{st.session_state.analysis}</div>', unsafe_allow_html=True)
    if st.button("✅ Confirm & Proceed", type="primary"):
        with st.spinner("🚀 Generating your custom interview path..."):
            prompt = "Generate 8 technical questions based on the candidate. One per line. No numbers."
            text = call_ai([{"role": "system", "content": prompt}, {"role": "user", "content": st.session_state.analysis}])
            if text:
                st.session_state.questions = [q.strip() for q in text.split('\n') if len(q.strip()) > 10][:8]
                st.session_state.answers = [""] * len(st.session_state.questions)
                st.session_state.current_q = 0
                st.session_state.step = 'interview'
                st.rerun()

@st.fragment
def interview_content():
    q_idx = st.session_state.current_q
    total = len(st.session_state.questions)
    
    st.progress((q_idx + 1) / total)
    st.write(f"**Step {q_idx + 1} of {total}** | {st.session_state.user_info.get('name', 'Candidate')} | 🕒 {st.session_state.interview_time}")

    c1, c2 = st.columns([3, 1], gap="small")
    with c1:
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        question = st.session_state.questions[q_idx]
        st.markdown(f'<div style="font-size: 1.4rem; font-weight: 700; color: #60a5fa; margin-bottom: 1rem;">{question}</div>', unsafe_allow_html=True)
        
        # Answer box syncs with session state
        ans = st.text_area("ans_box", value=st.session_state.answers[q_idx], height=180, key=f"ans_ta_{q_idx}", placeholder="Your answer...", label_visibility="collapsed")
        st.session_state.answers[q_idx] = ans
        
        col_prev, col_speak, col_next = st.columns([1, 1, 1])
        with col_prev:
            if st.button("⬅️ Back", disabled=(q_idx == 0), use_container_width=True):
                st.session_state.current_q -= 1
                st.rerun() # Fragment rerun only
        with col_speak:
            # Enhanced Speak button
            st.markdown(f"""
                <button id="speak-btn" onclick="startSpeech()" style="background: linear-gradient(135deg, #10b981, #059669); color: white; border: none; padding: 0.7rem; border-radius: 12px; width: 100%; cursor: pointer; font-weight: 700; transition: all 0.2s;">🎤 Speak</button>
                <script>
                    function startSpeech() {{
                        const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
                        if (!Recognition) {{ alert('Error: Speak is not supported in this browser.'); return; }}
                        const rec = new Recognition();
                        const btn = document.getElementById('speak-btn');
                        btn.style.background = '#ef4444'; btn.innerText = 'Listening...';
                        rec.onresult = (e) => {{
                            const transcript = e.results[0][0].transcript;
                            const findAndFill = (root) => {{
                                if (!root) return false;
                                const textareas = root.querySelectorAll('textarea');
                                for (let t of textareas) {{
                                    if (t.id && t.id.includes('ans_ta_')) {{
                                        t.value += (t.value ? ' ' : '') + transcript;
                                        t.dispatchEvent(new Event('input', {{ bubbles: true }}));
                                        return true;
                                    }}
                                }}
                                const iframes = root.querySelectorAll('iframe');
                                for (let f of iframes) {{ try {{ if (findAndFill(f.contentDocument)) return true; }} catch(e) {{}} }}
                                return false;
                            }};
                            let success = findAndFill(document);
                            if (!success) success = findAndFill(window.parent.document);
                            btn.style.background = 'linear-gradient(135deg, #10b981, #059669)'; btn.innerText = '🎤 Speak';
                        }};
                        rec.onerror = () => {{ btn.style.background = 'linear-gradient(135deg, #10b981, #059669)'; btn.innerText = '🎤 Speak'; }};
                        rec.start();
                    }}
                </script>
            """, unsafe_allow_html=True)
        with col_next:
            label = "Finish ✨" if q_idx + 1 == total else "Next ➡️"
            if st.button(label, use_container_width=True, type="primary"):
                if q_idx + 1 < total:
                    st.session_state.current_q += 1
                    st.rerun() # Fragment rerun only
                else:
                    # Final submission is a full page transition, will stop camera naturally but it's the end.
                    confirm_submission() 
        st.markdown('</div>', unsafe_allow_html=True)

    with c2:
        st.markdown('<div class="glass-card" style="padding: 1rem; text-align: center;">', unsafe_allow_html=True)
        st.write("📸 **Verification Preview**")
        if st.session_state.persistent_photo:
            st.image(st.session_state.persistent_photo, use_container_width=True)
        else:
            st.error("No verified photo!")
        st.markdown('</div>', unsafe_allow_html=True)

def show_interview():
    st.title("🎙️ Live Session")
    
    # 📹 Proctoring Camera (Static/Outside Fragment)
    # This keeps the camera active while the interview_content fragment reruns
    st.warning("⚠️ Proctoring is active. Do not look away or refresh.")
    c1, c2 = st.columns([1, 1])
    with c1:
        st.camera_input("Proctoring Feed", key="live_proctor_static", label_visibility="collapsed")
    with c2:
        st.info("Your session is being monitored for identity verification. Ensure adequate lighting.")
    
    st.divider()
    
    # Question & Navigation (Fragmented)
    if not st.session_state.questions:
        st.warning("Repairing questions flow...")
        if st.button("🔄 Restart Setup"): st.session_state.clear(); st.rerun()
        return

    interview_content()

def show_report():
    st.title("📊 Final Report")
    info = st.session_state.user_info
    
    with st.spinner("Generating summary..."):
        transcript = ""
        for i, (q, a) in enumerate(zip(st.session_state.questions, st.session_state.answers)):
            transcript += f"Q{i+1}: {q}\nA: {a}\n\n"
            
        res = call_ai([
            {"role": "system", "content": "Create report for Interview. YOU MUST START THE REPORT WITH 'RESULT: PASS' or 'RESULT: FAIL' based on performance, then provide details."},
            {"role": "user", "content": f"Candidate: {info.get('name', 'N/A')}\nID: {info.get('id', 'N/A')}\nEmail: {info.get('email', 'N/A')}\nDate: {st.session_state.interview_time}\n\nTranscript:\n{transcript}"}
        ])
    
    c1, c2 = st.columns([2, 1])
    with c1:
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        
        # UI Decision Badge
        is_pass = "PASS" in str(res).upper()
        badge_bg = "rgba(16, 185, 129, 0.2)" if is_pass else "rgba(239, 68, 68, 0.2)"
        badge_border = "#10b981" if is_pass else "#ef4444"
        badge_text = "🟢 RESULT: PASS" if is_pass else "🔴 RESULT: FAIL"
        
        st.markdown(f"""
            <div style="background: {badge_bg}; border: 1px solid {badge_border}; color: white; padding: 1rem; border-radius: 12px; text-align: center; margin-bottom: 2rem; font-weight: 800; font-size: 1.5rem; letter-spacing: 2px;">
                {badge_text}
            </div>
        """, unsafe_allow_html=True)

        st.write(f"### {info.get('name', 'Candidate')} (ID: {info.get('id', 'N/A')})")
        st.write(f"🕒 **Date:** {st.session_state.interview_time}")
        st.write(f"📧 {info.get('email', 'N/A')} | 📞 {info.get('phone', 'N/A')}")
        st.divider()
        if res:
            st.write(res)
            # PDF Generation with Photo
            try:
                pdf_bytes = create_pdf_report(info, res, transcript, st.session_state.persistent_photo)
                st.download_button(
                    label="📥 Download PDF",
                    data=pdf_bytes,
                    file_name=f"Interview_Report_{info.get('id', 'ID')}.pdf",
                    mime="application/pdf",
                    type="primary",
                    use_container_width=True
                )
            except Exception as e:
                st.error(f"PDF Export Error: {str(e)}")
                st.download_button("📥 Download TXT (Fallback)", transcript, file_name="Report.txt")
        st.markdown('</div>', unsafe_allow_html=True)
        
    with c2:
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        st.write("### Identity Captured")
        if st.session_state.persistent_photo:
            st.image(st.session_state.persistent_photo)
        st.markdown('</div>', unsafe_allow_html=True)

    if st.button("🔄 Start New"): st.session_state.clear(); st.rerun()

if st.session_state.step == 'setup': show_setup()
elif st.session_state.step == 'analysis': show_analysis()
elif st.session_state.step == 'interview': show_interview()
elif st.session_state.step == 'report': show_report()





